### ISSUE TITLE
build: there is nothing in the <body>

### ISSUE THREAD

**Issue by pascalandy** [ishan-me/svelte-tailwind-starter#1]
- `npm run dev` runs OK.

- `npm run build` seems Ok but there is nothing in the <body>

### index.html

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset='utf-8'>
	<meta name='viewport' content='width=device-width,initial-scale=1'>

	<title>Svelte app</title>

	<link rel='icon' type='image/png' href='/favicon.png'>
	<link rel='stylesheet' href='/global.css'>
	<link rel='stylesheet' href='/build/bundle.css'>
	<link rel="stylesheet" href="/index.css">

	<script defer src='/build/bundle.js'></script>
</head>

<body>
</body>
</html>
```

**Comment by isNan909** [comment]
Ok thanks for reporting this will look into this issue.

**Comment by isNan909** [comment]
I looked into this issue and looks like we wont have anything in the body tag instead its injected from our bundle file that we build. I personally have not used this setup configuration into production  but, looks like this takes effect once this is deployed to the server.

Also experimented with cloning a brand new svelte app and building it. And it's the same there too.

**Comment by pascalandy** [comment]
So I understand this is only for building node apps. I think you should mention it in your README. Thanks!
